# Generated by Django 2.2.2 on 2026-05-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_jcbpart'),
    ]

    operations = [
        migrations.AddField(
            model_name='jcbpart',
            name='category',
            field=models.CharField(choices=[('HYDRAULICS', 'Hydraulics'), ('POWERTRAIN', 'Powertrain (Engines & Transmission)'), ('GET', 'Ground Engaging Tools (Teeth & Blades)'), ('FILTERS', 'Filters'), ('ELECTRICAL', 'Electrical & Lighting'), ('CHASSIS', 'Chassis & Undercarriage'), ('OTHER', 'Other Spare Parts')], default='OTHER', max_length=20),
        ),
    ]
