# Generated by Django 3.2.25 on 2026-05-11 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_jcbpart_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=80)),
                ('contact_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('city', 'name'),
                'unique_together': {('name', 'city')},
            },
        ),
        migrations.CreateModel(
            name='VendorPartPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_prices', to='data.jcbpart')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_prices', to='data.vendor')),
            ],
            options={
                'ordering': ('part__category', 'part__name', 'vendor__city', 'vendor__name'),
                'unique_together': {('vendor', 'part')},
            },
        ),
    ]
