# Generated by GPT-5.2 on 2026-05-11

from decimal import Decimal, ROUND_HALF_UP

from django.db import migrations


def _deterministic_multiplier(seed: str) -> Decimal:
    # A stable pseudo-random-ish multiplier in [0.92, 1.14]
    total = sum(ord(c) for c in seed)
    pct = Decimal((total % 23) - 8) / Decimal(100)  # -0.08 .. +0.14
    return (Decimal("1.00") + pct).quantize(Decimal("0.0001"))


def seed_vendors_and_prices(apps, schema_editor):
    Vendor = apps.get_model("data", "Vendor")
    VendorPartPrice = apps.get_model("data", "VendorPartPrice")
    JCBPart = apps.get_model("data", "JCBPart")

    vendors = [
        ("Hydraulic House", "Pune", "+91 98765 43210"),
        ("JCB Spares Mart", "Mumbai", "+91 99887 76655"),
        ("Nashik Parts Hub", "Nashik", "+91 97654 32109"),
        ("Nagpur Earthmovers", "Nagpur", "+91 91234 56789"),
        ("Aurangabad Industrial", "Aurangabad", "+91 90909 80808"),
    ]

    vendor_objs = []
    for name, city, phone in vendors:
        v, _ = Vendor.objects.get_or_create(name=name, city=city, defaults={"contact_phone": phone})
        if not v.contact_phone and phone:
            v.contact_phone = phone
            v.save(update_fields=["contact_phone"])
        vendor_objs.append(v)

    # Seed prices from existing part master (so it’s “real” and consistent)
    hydraulics = list(JCBPart.objects.filter(category="HYDRAULICS").order_by("id")[:20])
    other = list(JCBPart.objects.exclude(category="HYDRAULICS").order_by("id")[:20])
    parts = hydraulics + other

    for part in parts:
        base = Decimal(str(part.price)).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)
        for v in vendor_objs:
            mult = _deterministic_multiplier(f"{part.part_number}|{v.name}|{v.city}")
            price = (base * mult).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)
            VendorPartPrice.objects.get_or_create(
                vendor=v,
                part=part,
                defaults={"price": price},
            )


def unseed_vendors_and_prices(apps, schema_editor):
    Vendor = apps.get_model("data", "Vendor")
    VendorPartPrice = apps.get_model("data", "VendorPartPrice")
    VendorPartPrice.objects.all().delete()
    Vendor.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0004_vendor_vendorpartprice"),
    ]

    operations = [
        migrations.RunPython(seed_vendors_and_prices, reverse_code=unseed_vendors_and_prices),
    ]

