# Generated by Django 3.2.25 on 2026-06-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_alter_jcbpart_image_360_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jcbpart',
            name='image_360_base',
            field=models.ImageField(blank=True, null=True, upload_to='360_images/'),
        ),
    ]
