# Generated by Django 3.2.25 on 2026-05-08 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daftarbarang',
            options={'verbose_name': 'JCB Part Inventory', 'verbose_name_plural': 'JCB Parts Inventory'},
        ),
        migrations.AlterModelOptions(
            name='daftartransaksi',
            options={'verbose_name': 'Sales Transaction', 'verbose_name_plural': 'Sales Transactions'},
        ),
        migrations.AlterModelOptions(
            name='listproducttransaksi',
            options={'verbose_name': 'Sales Product List', 'verbose_name_plural': 'Sales Product Lists'},
        ),
    ]
