# Generated by Django 3.2.25 on 2026-05-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0002_auto_20260508_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='daftarbarang',
            name='amt_incl_tax',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='daftarbarang',
            name='gst_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='daftarbarang',
            name='gst_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='daftarbarang',
            name='hsn_sac',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='daftarbarang',
            name='marp',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='daftarbarang',
            name='marp_last_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='daftarbarang',
            name='marp_last_amount_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='daftarbarang',
            name='marp_sell_val',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='daftarbarang',
            name='mrp',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='daftarbarang',
            name='part_for_what',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='daftarbarang',
            name='product_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='daftarbarang',
            name='vendor',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='daftarbarang',
            name='laba_persen',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='daftarbarang',
            name='nama_product',
            field=models.CharField(max_length=200),
        ),
    ]
