# Generated by Django 3.2.25 on 2026-05-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0003_auto_20260516_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='daftarbarang',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='inventory_images/'),
        ),
    ]
