# Generated by Django 3.2.25 on 2026-05-24 08:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('cashier', '0004_daftarbarang_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimateSlip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimate_no', models.CharField(max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('mobile_number', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
            options={
                'verbose_name': 'Estimate Slip',
                'verbose_name_plural': 'Estimate Slips',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='daftarbarang',
            name='company',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Company / Manufacturer'),
        ),
        migrations.AddField(
            model_name='daftarbarang',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Hidden', 'Hidden')], default='Active', max_length=10),
        ),
        migrations.CreateModel(
            name='FinancialInsightReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('mobile_number', models.CharField(blank=True, default='', max_length=15)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
            options={
                'verbose_name': 'Financial Insight Report',
                'verbose_name_plural': 'Financial Insight Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EstimateSlipItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particulars', models.CharField(max_length=300)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cashier.estimateslip')),
            ],
        ),
    ]
