# Generated by Django 3.2.25 on 2026-05-30 14:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0005_auto_20260524_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daftarbarang',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
