# Generated by Django 3.2.25 on 2026-06-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0006_alter_daftarbarang_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daftarbarang',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='jcb_parts/'),
        ),
    ]
